version: '2'

services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
     MYSQL_ROOT_PASSWORD: example
    volumes:
     - db_data:/env/db_data
  java:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'openjdk:8'
    working_dir: /app
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    volumes:
      - .:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
     - db
    ports:
     - 5555:80
    volumes:
     - phpmyadmin_data:/env
volumes:
  db_data:
    driver: local
  phpmyadmin_data:
    driver: local

